export const DEFAULT_CATEGORIES: Array<{
  name: string;
  type: "INCOME" | "EXPENSE";
  icon: string;
}> = [
  { name: "Gaji", type: "INCOME", icon: "💰" },
  { name: "Bonus", type: "INCOME", icon: "🎁" },
  { name: "Freelance", type: "INCOME", icon: "💻" },
  { name: "Hadiah", type: "INCOME", icon: "🎉" },
  { name: "Pendapatan Lain", type: "INCOME", icon: "💸" },
  { name: "Makan", type: "EXPENSE", icon: "🍜" },
  { name: "Kopi", type: "EXPENSE", icon: "☕" },
  { name: "Restoran", type: "EXPENSE", icon: "🍽️" },
  { name: "Delivery", type: "EXPENSE", icon: "🛵" },
  { name: "BBM", type: "EXPENSE", icon: "⛽" },
  { name: "Parkir", type: "EXPENSE", icon: "🅿️" },
  { name: "Tol", type: "EXPENSE", icon: "🛣️" },
  { name: "Transport Online", type: "EXPENSE", icon: "🚗" },
  { name: "Servis", type: "EXPENSE", icon: "🔧" },
  { name: "Belanja Rumah", type: "EXPENSE", icon: "🛒" },
  { name: "Listrik", type: "EXPENSE", icon: "💡" },
  { name: "Air", type: "EXPENSE", icon: "🚰" },
  { name: "Internet", type: "EXPENSE", icon: "🌐" },
  { name: "Gas", type: "EXPENSE", icon: "🔥" },
  { name: "Marketplace", type: "EXPENSE", icon: "📦" },
  { name: "Pakaian", type: "EXPENSE", icon: "👕" },
  { name: "Elektronik", type: "EXPENSE", icon: "📱" },
  { name: "Streaming", type: "EXPENSE", icon: "📺" },
  { name: "Game", type: "EXPENSE", icon: "🎮" },
  { name: "Hobby", type: "EXPENSE", icon: "🎨" },
  { name: "Rekreasi", type: "EXPENSE", icon: "🏖️" },
  { name: "Kesehatan", type: "EXPENSE", icon: "🏥" },
  { name: "Pendidikan", type: "EXPENSE", icon: "📚" },
  { name: "Personal Care", type: "EXPENSE", icon: "🧴" },
  { name: "Bank Fee", type: "EXPENSE", icon: "🏦" },
  { name: "Asuransi", type: "EXPENSE", icon: "🛡️" },
  { name: "Bunga", type: "EXPENSE", icon: "📈" },
  { name: "Lainnya", type: "EXPENSE", icon: "📌" },
];